import {StoreRole} from '@/types/entities';

export const rolesProvider: Array<StoreRole> = [
  {
    _id: 'ManageMedical',
    name: 'Quản lý Thuốc, Vật Tư',
    permissions: [
      'CreateMedical',
      'ReadMedical',
      'UpdateMedical',
      'DeleteMedical',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManagePrescription',
    name: 'Quản lý Đơn Thuốc',
    permissions: [
      'CreatePrescription',
      'ReadPrescription',
      'UpdatePrescription',
      'DeletePrescription',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageCategory',
    name: 'Quản lý Danh Mục',
    permissions: [
      'CreateCategory',
      'ReadCategory',
      'UpdateCategory',
      'DeleteCategory',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageTransaction',
    name: 'Quản lý Giao Dịch',
    permissions: [
      'CreateTransaction',
      'ReadTransaction',
      'UpdateTransaction',
      'DeleteTransaction',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageDiscount',
    name: 'Quản lý Chiết Khấu',
    permissions: [
      'CreateDiscount',
      'ReadDiscount',
      'UpdateDiscount',
      'DeleteDiscount',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManagePaymentMethod',
    name: 'Quản lý Phương Thức Thanh Toán',
    permissions: [
      'CreatePaymentMethod',
      'ReadPaymentMethod',
      'UpdatePaymentMethod',
      'DeletePaymentMethod',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManagePayment',
    name: 'Quản lý Thanh Toán',
    permissions: [
      'CreatePayment',
      'ReadPayment',
      'UpdatePayment',
      'DeletePayment',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ViewAnalytics',
    name: 'Xem Phân Tích',
    permissions: ['ReadAnalytics'],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageFeedback',
    name: 'Quản lý Feedback',
    permissions: [
      'CreateFeedback',
      'ReadFeedback',
      'UpdateFeedback',
      'DeleteFeedback',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ViewUpdateNews',
    name: 'Xem Tin Tức',
    permissions: ['ReadUpdateNews'],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ViewHistory',
    name: 'Xem Lịch Sử',
    permissions: ['ReadHistory'],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
];
export const rolesCustomer: Array<StoreRole> = [
  {
    _id: 'ManageMedical',
    name: 'Quản lý Thuốc, Vật Tư',
    permissions: [
      'CreateMedical',
      'ReadMedical',
      'UpdateMedical',
      'DeleteMedical',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManagePrescription',
    name: 'Quản lý Đơn Thuốc',
    permissions: [
      'CreatePrescription',
      'ReadPrescription',
      'UpdatePrescription',
      'DeletePrescription',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageCategory',
    name: 'Quản lý Danh Mục',
    permissions: [
      'CreateCategory',
      'ReadCategory',
      'UpdateCategory',
      'DeleteCategory',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageTransaction',
    name: 'Quản lý Giao Dịch',
    permissions: [
      'CreateTransaction',
      'ReadTransaction',
      'UpdateTransaction',
      'DeleteTransaction',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManagePayment',
    name: 'Quản lý Thanh Toán',
    permissions: [
      'CreatePayment',
      'ReadPayment',
      'UpdatePayment',
      'DeletePayment',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ViewAnalytics',
    name: 'Xem Phân Tích',
    permissions: ['ReadAnalytics'],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageFeedback',
    name: 'Quản lý Feedback',
    permissions: [
      'CreateFeedback',
      'ReadFeedback',
      'UpdateFeedback',
      'DeleteFeedback',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ViewUpdateNews',
    name: 'Xem Tin Tức',
    permissions: ['ReadUpdateNews'],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ViewHistory',
    name: 'Xem Lịch Sử',
    permissions: ['ReadHistory'],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
];
export const rolesSgod: Array<StoreRole> = [
  {
    _id: 'ManageDoctor',
    name: 'Quản lý Doctor',
    permissions: ['CreateDoctor', 'ReadDoctor', 'UpdateDoctor', 'DeleteDoctor'],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageProvider',
    name: 'Quản lý Provider',
    permissions: [
      'CreateProvider',
      'ReadProvider',
      'UpdateProvider',
      'DeleteProvider',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageHospitalManager',
    name: 'Quản lý Hospital',
    permissions: [
      'CreateHospitalManager',
      'ReadHospitalManager',
      'UpdateHospitalManager',
      'DeleteHospitalManager',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageSgodUser',
    name: 'Quản lý User SGOD',
    permissions: [
      'CreateSgodUser',
      'ReadSgodUser',
      'UpdateSgodUser',
      'DeleteSgodUser',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageFeedback',
    name: 'Quản lý Feedback',
    permissions: [
      'CreateFeedback',
      'ReadFeedback',
      'UpdateFeedback',
      'DeleteFeedback',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageMetadata',
    name: 'Quản lý Metadata',
    permissions: [
      'CreateMetadata',
      'ReadMetadata',
      'UpdateMetadata',
      'DeleteMetadata',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManagePaymentMethod',
    name: 'Quản lý Phương Thức Thanh Toán',
    permissions: [
      'CreatePaymentMethod',
      'ReadPaymentMethod',
      'UpdatePaymentMethod',
      'DeletePaymentMethod',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManagePayment',
    name: 'Quản lý Thanh Toán',
    permissions: [
      'CreatePayment',
      'ReadPayment',
      'UpdatePayment',
      'DeletePayment',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManagePackagePrice',
    name: 'Quản lý Package Price',
    permissions: [
      'CreatePackagePrice',
      'ReadPackagePrice',
      'UpdatePackagePrice',
      'DeletePackagePrice',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageDefaultValidTo',
    name: 'Quản lý ValidTo',
    permissions: [
      'CreateDefaultValidTo',
      'ReadDefaultValidTo',
      'UpdateDefaultValidTo',
      'DeleteDefaultValidTo',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ViewAnalytics',
    name: 'Xem Phân Tích',
    permissions: ['ReadAnalytics'],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ManageUpdateNews',
    name: 'Quản Lý Tin Tức',
    permissions: [
      'CreateUpdateNews',
      'ReadUpdateNews',
      'UpdateUpdateNews',
      'DeleteUpdateNews',
    ],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
  {
    _id: 'ViewHistory',
    name: 'Xem Lịch Sử',
    permissions: ['ReadHistory'],
    icon_color: 'primary',
    icon: 'Medical',
    parent_role_id: '',
    type: 'Provider',
    created_by: 'Sgod',
  },
];
